baseURL = "http://hugo.crewert.com/"
languageCode = "en-us"
title = "CREEEwerts Hugo Site"
author = "CREEEwert"
theme = "flex"
defaultContentLanguage = "en"
sectionPagesMenu = "main"
paginate = 3 # this is set low for demonstrating
enableRobotsTXT = true

[params]
  author = "C.R. Ewert"
  recent_posts_number = 8

